title: Laura Gonzaga
description: Portfólio de Projetos em BI e Data Analytics
baseurl: ""
url: "https://lauragonzaga.github.io"

collections_dir: _collections
collections:
  projetos:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"